spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.105.170.25:3306/es?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
